### ISSUE TITLE
Only see 4.15-rc1 on Linux Mint 18.3

### ISSUE THREAD

**Issue by InAnimaTe** [teejee2008/ukuu#51]
![sadface](https://user-images.githubusercontent.com/1192726/35896257-5b3d8afe-0b89-11e8-8dbb-456ebe82884e.png)

```
┌[mloria@aquarius] 
└[~]> uname -a
Linux aquarius 4.14.2-041402-generic #201711240330 SMP Fri Nov 24 08:32:52 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
┌[mloria@aquarius] 
└[~]> cat /etc/os-release 
NAME="Linux Mint" 
VERSION="18.3 (Sylvia)" 
ID=linuxmint 
ID_LIKE=ubuntu 
PRETTY_NAME="Linux Mint 18.3" 
VERSION_ID="18.3" 
HOME_URL="http://www.linuxmint.com/" 
SUPPORT_URL="http://forums.linuxmint.com/" 
BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/" 
VERSION_CODENAME=sylvia 
UBUNTU_CODENAME=xenial 

```

**Comment by gothicVI** [comment]
What happens if you refresh manually or via terminal?

**Comment by InAnimaTe** [comment]
I've tried that multiple times as well as reinstalling to no avail :(

**Comment by gothicVI** [comment]
Try removing ~/.cache/ukuu

**Comment by InAnimaTe** [comment]
Yep, that worked. I now see up to 4.15.2. Is this a larger issue that should actually be fixed in the code so it doesn't happen again?

**Comment by InAnimaTe** [comment]
I've always used the UI to interact with Ukuu. When I went to delete the cache, I did need to sudo.

**Comment by gothicVI** [comment]
So the culprit comes about as follows: whenever you install a new kernel the packages are downloaded not as user but as root since the installation ask for root rights from the very get go and thus the packages as well as eventually the index files belong to root and you'd need sudo in order to delete the folder's content.
That should be fixed: no longer download as root since that's a security flaw anyway. Only invoke root rights when it actually comes to the installation.

**Comment by InAnimaTe** [comment]
I completely agree. Let me know if I can be of help in pushing this forward i.e. testing etc.. Love Ukuu and definitely want to help make it better.

**Comment by c-edw** [comment]
@gothicVI Getting the same issue here where 4.17-rc3 won't show up. Deleting `~/.cache/ukuu` has not resolved the problem. I was able to get it to show up for a while, but it disappeared after trying to install it.

**Comment by gothicVI** [comment]
@c-edw have you additionally tried deleting /tmp/ukuu* together with ~/.cache/ukuu? That sometimes does it for me - although the problem keeps coming back...

**Comment by c-edw** [comment]
@gothicVI I can now see the 4.17-rc3 kernel in the Ukuu GUI, but attempting to install it doesn't work. Looks like it's failing to fetch the kernel headers. Additionally, Ukuu closes when doing some operations such as removing a kernel version, but I believe there's already an issue open for this.

**Comment by gothicVI** [comment]
@c-edw that might be related to https://github.com/teejee2008/ukuu/issues/69
