### ISSUE TITLE
Ukuu hangs during installation

### ISSUE THREAD

**Issue by jgoodleaf** [teejee2008/ukuu#81]
Running `ukuu --install v4.16.15` produces this: 
`ukuu v18.5.1
Distribution: Ubuntu 18.04 LTS
Architecture: amd64
Running kernel: 4.16.10-041610-generic
Kernel version: 4.16.10-041610-generic
Cache: /home/jgoodleaf/.cache/ukuu
Temp: /tmp/ukuu/ATD73zUy
----------------------------------------------------------------------
Found installed: 4.15.0.23.25
Found installed: 4.15.0-22.24
Found installed: 4.15.0-23.25
Found installed: 4.16.10-041610.201805190530
----------------------------------------------------------------------
Preparing to install 'v4.16.15'

Selecting previously unselected package linux-headers-4.16.15-041615-generic.
(Reading database ... 467880 files and directories currently installed.)
Preparing to unpack linux-headers-4.16.15-041615-generic_4.16.15-041615.201806111730_amd64.deb ...
Unpacking linux-headers-4.16.15-041615-generic (4.16.15-041615.201806111730) ...
Selecting previously unselected package linux-modules-4.16.15-041615-generic.
Preparing to unpack linux-modules-4.16.15-041615-generic_4.16.15-041615.201806111730_amd64.deb ...
Unpacking linux-modules-4.16.15-041615-generic (4.16.15-041615.201806111730) ...
Selecting previously unselected package linux-image-unsigned-4.16.15-041615-generic.
Preparing to unpack linux-image-unsigned-4.16.15-041615-generic_4.16.15-041615.201806111730_amd64.deb ...
Unpacking linux-image-unsigned-4.16.15-041615-generic (4.16.15-041615.201806111730) ...
Selecting previously unselected package linux-headers-4.16.15-041615.
Preparing to unpack linux-headers-4.16.15-041615_4.16.15-041615.201806111730_all.deb ...
Unpacking linux-headers-4.16.15-041615 (4.16.15-041615.201806111730) ...
Setting up linux-modules-4.16.15-041615-generic (4.16.15-041615.201806111730) ...
Setting up linux-image-unsigned-4.16.15-041615-generic (4.16.15-041615.201806111730) ...
I: /vmlinuz.old is now a symlink to boot/vmlinuz-4.15.0-23-generic
I: /initrd.img.old is now a symlink to boot/initrd.img-4.15.0-23-generic
I: /vmlinuz is now a symlink to boot/vmlinuz-4.16.15-041615-generic
I: /initrd.img is now a symlink to boot/initrd.img-4.16.15-041615-generic
Setting up linux-headers-4.16.15-041615 (4.16.15-041615.201806111730) ...
Setting up linux-headers-4.16.15-041615-generic (4.16.15-041615.201806111730) ...
`
This appears to hang indefinitely. I thought at first that I had inadvertently put the system to sleep during installation, but I removed the kernel entirely and have re-executed. Same thing. It hangs exactly at this spot without returning an error. The machine is almost entirely idle, so it is not a matter of system resources, and this process appears not to be using any CPU. (It's also not responsive to CTRL+C.)

**Comment by jgoodleaf** [comment]
Hmmm. Update. There may be something wrong with my system, though I'm not sure what, nor how to debug it. 
After issuing `apt upgrade` we're hanging on the DKMS module rebuild...
```
DEBUG:Parsing /usr/share/ubuntu-drivers-common/quirks/put_your_quirks_here
Loading new nvidia-390.67 DKMS files...
Building for 4.16.10-041610-generic
Building for architecture x86_64
Building initial module for 4.16.10-041610-generic

```

**Comment by sophiv** [comment]
I also encoutered the same problem in Ubuntu 18.04. I felt so confused. Did you have solve this problem ? .....

**Comment by sophiv** [comment]
hanging message:
Loading new nvidia-390.67 DKMS files...
Building for 4.15.0-23-generic
Building for architecture x86_64
Building initial module for 4.15.0-23-generic

**Comment by sophiv** [comment]
Ok, I got it! guys! This is because your machine is running in secure boot mode, in fact, the "Building initial module for 4.15.0-23-generic" operation asks you to input the password for authorization but without any PROMPT!!! When stucking here, input your password and hit enter twice, it will pass!!!

**Comment by jgoodleaf** [comment]
How did you figure that out?

**Comment by gothicVI** [comment]
@jgoodleaf I assume by "manually" installing the packages via `sudo dpkg -i *.deb` in the respective `.cache/ukuu/v4.15.0/amd64` directory.

**Comment by sophiv** [comment]
@jgoodleaf I found the similar topic published in 2006 from a forum, as so, I tried and it was solved ..

**Comment by LeSyl21** [comment]
Hi all, I have find the solution.
debconf use whiptail for ask you enroll MOK password. but it doesn't work with ukuu.
Just open a term use "export DEBIAN_FRONTEND=readline" when launch ukuu or ukuu-gtk
It work in cli for me hasn't test with GTK.
If somebody know how to add this variable in source code :-D
Bye

**Comment by jozuenoon** [comment]
Hi! None of above works for me on Ubuntu Bionic any idea?

**Comment by LeSyl21** [comment]
Hi jozuenoon,

You can found information here: https://www.debian.org/releases/stable/s390x/ch05s02.html.fr

You have:
    DEBIAN_FRONTEND=noninteractive (PROBABLY DON'T WORK BECAUSE MOK WAIT INFO)
    DEBIAN_FRONTEND=text (RECOMMANDED FOR SERIAL INSTALL) <- try it
    DEBIAN_FRONTEND=newt (DEFAULT)
    DEBIAN_FRONTEND=gtk (MAYBE WORK IF YOU HAVE A X)

Sorry but I can't investigate, I don't use UKUU anymore for the moment...

**Comment by Jakethethird** [comment]
I have this issue on my laptop, but only when running on Wayland. If I log out and log back in with Xorg, then it completes. 

I am running `xhost si:localuser:root` upon log in via start up applications in the Wayland session. This allows Gparted and Synaptic to work (they require root access), but it doesn't fix this issue in UKUU.
